import {
    FieldLabel,
    HiddenText,
    Separator
} from "@pcd/passport-ui";
import styled from "styled-components";
import { NoirPCD } from "./NoirPCD";
  
  export function NoirCardBody({
    pcd,
  }: {
    pcd: NoirPCD;
  }) {
    return (
      <Container>
        <p>
          This PCD represents a particular Noir Proof that has been generated by a
          particular Semaphore Identity.
        </p>
  
        <Separator />
  
        <FieldLabel>Proof</FieldLabel>
        <HiddenText text={pcd.claim.proof} />
      </Container>
    );
  }
  
  const Container = styled.div`
    padding: 16px;
    overflow: hidden;
    width: 100%;
  `;
  